version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/apache2/Dockerfile
    image: melhor-envio-app
    container_name: melhor-envio-app
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
  db:
    env_file:
      - ./.env
    image: mysql:8.0.21
    container_name: melhor-envio-db
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db:/var/lib/mysql
  redis:
    build:
      context: .
      dockerfile: .docker/redis/Dockerfile
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./:/redis/data
    image: ${REDIS_NAME}
    container_name: ${REDIS_NAME}
    depends_on:
      - "postgres"
